services:
  - type: web
    name: word-game-api
    env: python
    buildCommand: cd server && pip install -r requirements-prod.txt
    startCommand: cd server && gunicorn -w 1 -k uvicorn.workers.UvicornWorker --timeout 300 --keep-alive 5 --log-level debug --worker-class uvicorn.workers.UvicornWorker --worker-connections 1000 --forwarded-allow-ips="*" --proxy-protocol --proxy-allow-from="*" main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /words